### ISSUE TITLE
InlineCommentSpacingSniff - vyžadovat i mezeru (nebo odřádkování) před komentářem

### ISSUE THREAD

**Issue by nufue** [InspireCZ/coding-standard-sniffs#2]
![image](https://github.com/user-attachments/assets/7f5a1ada-1f83-432b-b839-9d1b39a2e5f5)

Mezeru za to doplní pěkně. Mezeru před ne.

A ještě mě napadlo, jestli celkově nezakázat komentáře pomocí `#` - obecně je moc nepoužíváme.

**Comment by mlutonsky** [comment]
Fixed by https://github.com/InspireCZ/coding-standard-sniffs/releases/tag/v1.4.0
